version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: openwebui
      POSTGRES_PASSWORD: secretpassword
      POSTGRES_DB: openwebui
    volumes:
      - postgres_data:/var/lib/postgresql/data

  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
    restart: unless-stopped
    entrypoint: >
      sh -c "
        ollama serve &
        sleep 5 &&
        ollama pull llama3 &&
        tail -f /dev/null
      "

  openwebui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: openwebui
    restart: unless-stopped
    environment:
      - DATABASE_URL=postgresql://openwebui:secretpassword@postgres:5432/openwebui
      - OLLAMA_BASE_URL=http://ollama:11434
      - HOST=0.0.0.0
      - GLOBAL_LOG_LEVEL=DEBUG
#      - HTTPX_LOG_LEVEL=DEBUG
#      - LOG_LEVEL=DEBUG
#      - LOGURU_LEVEL=DEBUG
    ports:
      - "3000:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - postgres
      - ollama

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - xpack.monitoring.collection.enabled=true
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elastic_data:/usr/share/elasticsearch/data
    restart: unless-stopped

  kibana:
    image: docker.elastic.co/kibana/kibana:8.13.4
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    restart: unless-stopped

volumes:
  postgres_data:
  ollama_data:
  elastic_data:
